# Generated by Django 3.2.9 on 2021-12-26 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('offer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('offer_percent', models.IntegerField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('offer_status', models.CharField(blank=True, default=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=100, null=True)),
                ('offer_percent', models.IntegerField()),
                ('expiry_date', models.DateField()),
                ('expiry_time', models.TimeField(blank=True, null=True)),
                ('offer_status', models.CharField(blank=True, default=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_category_name', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('catergory_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='categorymanagement.category')),
            ],
        ),
    ]
