"""
Django settings for ecomproject project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

from django.contrib.messages import constants as messages

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0%a6&oj--q-h11qclrwv2l20eb55=l*36$&x4lpjk11vab-#*#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'useraccount.apps.UseraccountConfig',
    'admin.apps.AdminConfig',
    'adminusermanagement.apps.AdminusermanagementConfig',
    'categorymanagement.apps.CategorymanagementConfig',
    'productmanagement.apps.ProductmanagementConfig',
    'product_store.apps.ProductStoreConfig',
    'cart.apps.CartConfig',
    'order_management.apps.OrderManagementConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ecomproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processor.counter',
                'order_management.context_processor.offer_expiry',
                'product_store.context_processor.category_display',
                'order_management.context_processor.coupon_expiry',
                'cart.context_processor.wishlist_counter',
                'cart.context_processor.saved_amount',

            ],
        },
    },
]

WSGI_APPLICATION = 'ecomproject.wsgi.application'

AUTH_USER_MODEL = 'useraccount.Accounts'

# razor pay


RAZOR_KEY_ID = 'rzp_test_ua5R6cpSZPCqaE'
RAZOR_KEY_SECRET = 'PngaNZnBNJpoBOz4KSeCOhg0'

# Twilio

TWILIO_SERVICE_SID = 'VA588549f1ff7e8eaaebb9c800d7ea9744'
ACCOUNT_SID = 'ACfaa078cba3798f7e74284ef8d16f13e0'
TWILIO_AUTH_TOKEN = 'fb52e3db2a4599b8f7fd4dabdac8413d'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'sample',
        'USER': 'postgres',
        'PASSWORD': '0102',
        'HOST': 'localhost'

    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')

]
STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# MEDIA FILES CONFIGURATION

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

DATA_UPLOAD_MAX_MEMORY_SIZE = 10242880


